### ISSUE TITLE
Consider moving this repo to the image-rs organisation

### ISSUE THREAD

**Issue by lovasoa** [image-rs/jpeg-decoder#105]
It looks like this quite fundamental crate is maintained by a single person (@kaksmet). Maybe it should be moved to the [image-rs](https://github.com/image-rs/) organization ? It would give more people push access, and should lower the risk of this crate being abandoned.

**Comment by kaksmet** [comment]
jpeg-decoder is now part of the image-rs organisation.

**Comment by lovasoa** [comment]
Great !
Would you be ok with also giving the image-rs organization publish rights to this crate on crates.io ?

**Comment by kaksmet** [comment]
They have been invited as owners of the crate on crates.io
image-rs/organization#9
