### ISSUE TITLE
Move the CI from travis to github actions

### ISSUE THREAD

**Issue by lovasoa** [image-rs/jpeg-decoder#141]
Hello,
  Would you be interested in moving the CI for this project from travis to github actions ? Currently, the CI is super slow, and this makes the management of pull requests less smooth than it could be.
  If you are interested, I'm ready to make a PR that creates the necessary github action workflow files.

**Comment by HeroicKatora** [comment]
One thing to keep in mind is that Actions only support Linux containers.

**Comment by HeroicKatora** [comment]
Sure, go ahead if this is possible or just try it out. The slowness with Travis is partially because it shares all community runners between the organization. I've also observed that its container setup is incredibly slow and has basically no caching.
