### ISSUE TITLE
Need decoded

### ISSUE THREAD

**Issue by douglasgromerjr** [image-rs/jpeg-decoder#170]
url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAQAAAAD+Fb1AAAAGUlEQVR4AWP8zwADxgzG/xmA3P9AAGLApQC0NgpfF9g/mgAAAABJRU5ErkJggg==")

**Comment by fintelia** [comment]
That seems to be a base64 encoded PNG file while this crate only deals with JPEGs. You should however be able to open it (say with the [png crate](https://github.com/image-rs/image-png)) if you first run...
```bash
echo "iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAQAAAAD+Fb1AAAAGUlEQVR4AWP8zwADxgzG/xmA3P9AAGLApQC0NgpfF9g/mgAAAABJRU5ErkJggg==" | base64 -d > test.png
```
