### ISSUE TITLE
Lossless JPEG

### ISSUE THREAD

**Issue by vsaase** [image-rs/jpeg-decoder#191]
Hi,

in the medical community the Lossless JPEG format (SOF type 0xc3, not JPEG-LS or JPEG2000) is very popular due to the DICOM standard.
It is used for graytone images, 16 bit or 12 bit most of the time. 

Some links:
- https://en.wikipedia.org/wiki/Lossless_JPEG
- https://www.w3.org/Graphics/JPEG/itu-t81.pdf

Implementations of JPEG Lossless (SOF type 0xc3):
- https://github.com/malaterre/GDCM/tree/master/Utilities/gdcmjpeg
- same as https://github.com/DCMTK/dcmtk/tree/master/dcmjpeg ?
- https://github.com/rordenlab/dcm2niix/blob/master/console/jpg_0XC3.cpp
- https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/codecs/jpegLossless.js

Is anyone aware of Rust implementations? Is there maybe a quick way to do it using existing code of this library? Probably the main difficulty would be to support 16 bit?

**Comment by vsaase** [comment]
I now implemented Lossless decoding in my fork: https://github.com/vsaase/jpeg-decoder/tree/lossless

This is at the moment however a breaking change, as the `decode` function returns u16 instead of u8 and also internally data is now u16. We could use generics to support both.

**Comment by fintelia** [comment]
Other image-rs crates use `&[u8]` slices to store pixel data, even when the pixels themselves are u16's or f32's. Think that could work here?

**Comment by vsaase** [comment]
Ok, I changed it so that for 16bit images `decode` now returns big endian u8 bytes, like the png crate.

**Comment by fintelia** [comment]
If possible, native endian would be preferable to big endian. In the main image crate we actually end up having to [swap the byte order for PNG's](https://github.com/image-rs/image/blob/f904a581640dedbbb1e8e5d963761933a4163691/src/codecs/png.rs#L229-L241)

**Comment by vsaase** [comment]
I also prefer native endian, changed it.

**Comment by Shnatsel** [comment]
Lossless JPEG has been implemented in #193; I believe this issue can be closed.
