### ISSUE TITLE
Speed is half of normal jpeg decoders (on ARM)

### ISSUE THREAD

**Issue by fzyzcjy** [image-rs/jpeg-decoder#202]
Hi thanks for the lib! However, the speed of this library seems to be half of normal jpeg decoders. When running on ARM, normal decoder uses 600ms to decode a 4000x3000 color JPEG, while this lib uses 1100ms.

**Comment by veluca93** [comment]
@HeroicKatora I have noticed that NEON intrinsics are currently only available on nightly. I can think of 3 options for adding SIMD support on NEON, and I'm not sure which is the best.

- Use an external `asm` file that contains the NEON-specific code. This would work, but it's a huge pain (among other things, one needs to care about calling conventions and the like...)
- Use an external `c` file containing functions implemented with intrinsics. I believe this is entirely superior to the `asm` approach.
- Only support NEON on nightly. By far the easiest option, and saves us the pain of writing the CPU detection code if we want to support arm and not just aarch64...

What are your thoughts?

**Comment by fintelia** [comment]
How likely is it that the NOEN intrinsics will be stabilized in their current form? If it is just a matter of waiting for them to reach stable, then I think that's probably the best option. We'd just leave it behind a feature flag until they were available on stable at our MSRV.

What worries more is the testing/maintenance strategy given that the CI and most developers' machines are currently x86. (Not a deal-breaker mind you, just something to figure out so we don't find ourselves scrambling to track down an ARM machine because we need to test an urgent patch or something).

**Comment by HeroicKatora** [comment]
Regarding NEON, I wonder if it were possible to convince LLVM to auto-vectorize enough and in particular utilizing instructions. We can have specialized methods with explicit `target_feature(enable = "…")` annotations. For example, consider and compare the instruction output here:

```rust
#[target_feature(enable = "avx2")]
pub unsafe fn sum_sse3(vec: &[u32]) -> u32 {
    let mut n = 0u32;
    for &i in vec {
        n = n.wrapping_add(i);
    }
    n
}

pub fn sum_me(vec: &[u32]) -> u32 {
    let mut n = 0u32;
    for &i in vec {
        n = n.wrapping_add(i);
    }
    n
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=ad6589aa8a8c9430ac51eaa9b761c40a)

**Comment by HeroicKatora** [comment]
Ah well, looks like the feature names and annotation for ARM aren't stable either. <https://rustc.godbolt.org/z/bcr59rTaa>
Kind of odd that the pure codegen appears to be tied so closely to the stabilization of the `arch` module intrinsics, isn't it?

**Comment by veluca93** [comment]
In my experience, for this kind of code, autovectorization doesn't really
bring you far enough...

I'll give it a try in the next few days and we can see where to go from
there.

**Comment by paolobarbolini** [comment]
> Regarding NEON, I wonder if it were possible to convince LLVM to auto-vectorize enough and in particular utilizing instructions.

I'm not a fan of proc macros but it might be worth to at least give it a try via the [multiversion crate](https://docs.rs/multiversion/0.6.1/multiversion/#example)
