### ISSUE TITLE
Crashtests don't actually use the result

### ISSUE THREAD

**Issue by filipl** [image-rs/jpeg-decoder#99]
At the end of crashtest() the result is not looked at. If I unwrap() the result a lot of the tests fail. I'm not sure whether or not they should fail, but I'd assume they should pass since the test would be expecting an Err otherwise.

```
let file = File::open(path).unwrap();
let mut decoder = jpeg::Decoder::new(BufReader::new(file));
let _ = decoder.decode();
```

**Comment by HeroicKatora** [comment]
The crash test is used to find instances of panicking, not of erroneous decoding. Faulty images are expected and relevant, as even maliciously constructed image should not affect the stability of programs using the library. Thus, we ignore the error and only check if the point is reached at all without panicking.

**Comment by lovasoa** [comment]
wouldn't it be clearer if the test asserted that the result is an error, rather than just ignoring it?

**Comment by HeroicKatora** [comment]
Faulty images are expected but not all images are necessarily faulty. Some of the tests might be for overflows during decoding a valid image etc. Similar code, ignoring the error, can be found in all our fuzzer tests as well.
